# .github/workflows/release.yml
name: Build and publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-package:
    name: Build Python 🐍package 📦 and upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pypa/setuptools
        run: |
          python -m pip install wheel
      - name: Build a binary wheel
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
